package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Tailwind Design Tokens for JanSetu AI
val SurfaceContainerLowest = Color(0xFFffffff)
val SeverityHigh = Color(0xFFF97316)
val OnSecondaryFixed = Color(0xFF131f00)
val SeverityCritical = Color(0xFFDC2626)
val OutlineVariant = Color(0xFFc3c8c2)
val OnPrimaryContainer = Color(0xFF77887c)
val PrimaryContainer = Color(0xFF101f16)
val Surface = Color(0xFFf8faf7)
val Secondary = Color(0xFF476800)
val SurfaceContainer = Color(0xFFeceeeb)
val SurfaceCard = Color(0xFFFFFFFF)
val OnErrorContainer = Color(0xFF93000a)
val OnError = Color(0xFFffffff)
val OutlineColor = Color(0xFF737874)
val SuccessGreen = Color(0xFF16A34A)
val SurfaceDim = Color(0xFFd8dbd8)
val OnSurface = Color(0xFF191c1b)
val OnTertiary = Color(0xFFffffff)
val OnPrimary = Color(0xFFffffff)
val OnTertiaryFixedVariant = Color(0xFF3e4941)
val OnSecondary = Color(0xFFffffff)
val OnBackground = Color(0xFF191c1b)
val SurfaceBright = Color(0xFFf8faf7)
val Primary = Color(0xFF000000)
val TertiaryFixed = Color(0xFFd9e6db)
val SurfaceContainerHigh = Color(0xFFe7e9e6)
val TertiaryContainer = Color(0xFF131e17)
val TertiaryFixedDim = Color(0xFFbdcabf)
val PrimaryFixedDim = Color(0xFFb9cbbe)
val InverseSurface = Color(0xFF2e312f)
val SecondaryFixedDim = Color(0xFF99da00)
val OnTertiaryContainer = Color(0xFF7b877d)
val SecondaryFixed = Color(0xFFaff800) // Neon Green
val SurfaceContainerLow = Color(0xFFf2f4f1)
val PrimaryFixed = Color(0xFFd5e7d9)
val OnPrimaryFixedVariant = Color(0xFF3b4a40)
val OnTertiaryFixed = Color(0xFF131e17)
val OnPrimaryFixed = Color(0xFF101f16)
val SurfaceVariant = Color(0xFFe1e3e0)
val SurfaceContainerHighest = Color(0xFFe1e3e0)
val ErrorColor = Color(0xFFba1a1a)
val SurfaceTint = Color(0xFF526258)
val OnSecondaryContainer = Color(0xFF4b6d00)
val InverseOnSurface = Color(0xFFeff1ee)
val SecondaryContainer = Color(0xFFadf500)
val BackgroundColor = Color(0xFFf8faf7)
val InversePrimary = Color(0xFFb9cbbe)
val OnSecondaryFixedVariant = Color(0xFF354e00)
val OnSurfaceVariant = Color(0xFF434844)
val Tertiary = Color(0xFF000000)
val ErrorContainer = Color(0xFFffdad6)
val WarningYellow = Color(0xFFFACC15)

// Additional dark theme custom
val DarkBackground = Color(0xFF0B1A12) // Main background in splash and dark mode
val DarkSurfaceHighest = Color(0xFF12231A) // Equivalent to surface-container-highest in dark
val NeonGlow = Color(0x26B4FF00) // rgba(180, 255, 0, 0.15)

// Legacy Colors (To be replaced during phased migration)
val PrimaryBlue = Color(0xFF2563EB)
val DarkBlue = Color(0xFF0F172A)
val LightBlue = Color(0xFFEFF6FF)
val HighSeverityOrange = Color(0xFFF97316)
val CriticalRed = Color(0xFFDC2626)
val CardWhite = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF0F172A)
val TextSecondary = Color(0xFF64748B)
val BorderColor = Color(0xFFE2E8F0)
val DarkPrimary = Color(0xFF60A5FA)
val DarkSurface = Color(0xFF1E293B)
val DarkTextPrimary = Color(0xFFF8FAFC)
val DarkTextSecondary = Color(0xFF94A3B8)
val DarkBorder = Color(0xFF334155)
